name: Check Winning
on:
  schedule:
    - cron: 0 22 * * 6  # 매주 토요일 오후 10시, 한국시간은 UTC+9 => 매주 일요일 오전 7시 (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Check Winning
    steps:  

      - uses: actions/checkout@v3    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Run Scripts
        run: make check
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COUNT_WIN: ${{ secrets.COUNT_WIN }}
          COUNT_LOTTO: ${{ secrets.COUNT_LOTTO }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL:  ${{ secrets.DISCORD_WEBHOOK_URL }}
          TELEGRAM_BOT_TOKEN_FOR_LOTTERY: ${{ secrets.TELEGRAM_BOT_TOKEN_FOR_LOTTERY }}
          TELEGRAM_BOT_CHAT_ID: ${{ secrets.TELEGRAM_BOT_CHAT_ID }}
